### ISSUE TITLE
Pre-trained model wanted

### ISSUE THREAD

**Issue by lilin-hitcrt** [MaverickPeter/DiSCO-pytorch#1]
Hi, thanks for your great work!
I am very interested in DiSCO and want to test this code. I would be very grateful if you can provide some pre-trained models.
Thank you and great work!

**Comment by MaverickPeter** [comment]
I upload a model trained on NCLT dataset with occupied BEV feature to google drive, the link is https://drive.google.com/file/d/1VU9OtA0Q9t0nht5GcDc_0qQ9bVEit2lP/view?usp=sharing

**Comment by lilin-hitcrt** [comment]
> I upload a model trained on NCLT dataset with occupied BEV feature to google drive, the link is https://drive.google.com/file/d/1VU9OtA0Q9t0nht5GcDc_0qQ9bVEit2lP/view?usp=sharing
Thanks for your quick reply! But I found that I don’t have permission to access this link.

**Comment by MaverickPeter** [comment]
> > I upload a model trained on NCLT dataset with occupied BEV feature to google drive, the link is https://drive.google.com/file/d/1VU9OtA0Q9t0nht5GcDc_0qQ9bVEit2lP/view?usp=sharing
> > Thanks for your quick reply! But I found that I don’t have permission to access this link.

sorry for the permission issue, I update the permissions, now you can download it.

**Comment by lilin-hitcrt** [comment]
> > > I upload a model trained on NCLT dataset with occupied BEV feature to google drive, the link is https://drive.google.com/file/d/1VU9OtA0Q9t0nht5GcDc_0qQ9bVEit2lP/view?usp=sharing
> > > Thanks for your quick reply! But I found that I don’t have permission to access this link.
> 
> sorry for the permission issue, I update the permissions, now you can download it.
I have successfully downloaded the model. thank you very much！
