### ISSUE TITLE
Questions about gpuadder

### ISSUE THREAD

**Issue by lilin-hitcrt** [MaverickPeter/DiSCO-pytorch#2]
Hello!
When I test infer.py, there was a problem that 'gpuadder' could not be found. Then I used ctyps to load the ‘gpuadder.cpython-37m-x86_64-linux-gnu.so’, but there was still an error that the function ‘GPUTransformer’ could not be found.

The added code is as follows:
gpuadder=ctypes.cdll.LoadLibrary('./gpuadder.cpython-37m-x86_64-linux-gnu.so')

The output is:
Traceback (most recent call last):
  File "/home/l/workspace/python/DiSCO-pytorch/inference.py", line 216, in <module>
    disco = infer(cfg.INPUT_FILENAME)
  File "/home/l/workspace/python/DiSCO-pytorch/inference.py", line 37, in infer
    query = load_pc_file_infer(input_filename)
  File "/home/l/workspace/python/DiSCO-pytorch/loading_pointclouds.py", line 93, in load_pc_file_infer
    transer = gpuadder.GPUTransformer(pc, size, cfg.max_length, cfg.num_ring, cfg.num_sector, cfg.num_height, 1)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./gpuadder.cpython-37m-x86_64-linux-gnu.so: undefined symbol: GPUTransformer

**Comment by MaverickPeter** [comment]
You may try to add path to the system path to include gpuadder, I suggest not use the cdll load api.

**Comment by lilin-hitcrt** [comment]
> You may try to add path to the system path to include gpuadder, I suggest not use the cdll load api.
I found that it is included in the sys path but still cannot be loaded.

['/home/l/workspace/python/DiSCO-pytorch', '/home/l/workspace/catkin_ws/devel/lib/python2.7/dist-packages', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/home/l/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/home/l/workspace/python/DiSCO-pytorch']
Traceback (most recent call last):
  File "/home/l/workspace/python/DiSCO-pytorch/inference.py", line 24, in <module>
    from loading_pointclouds import *
  File "/home/l/workspace/python/DiSCO-pytorch/loading_pointclouds.py", line 11, in <module>
    import gpuadder
ModuleNotFoundError: No module named 'gpuadder'

**Comment by MaverickPeter** [comment]
> > You may try to add path to the system path to include gpuadder, I suggest not use the cdll load api.
> > I found that it is included in the sys path but still cannot be loaded.
> 
> ['/home/l/workspace/python/DiSCO-pytorch', '/home/l/workspace/catkin_ws/devel/lib/python2.7/dist-packages', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/home/l/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/home/l/workspace/python/DiSCO-pytorch']
> Traceback (most recent call last):
> File "/home/l/workspace/python/DiSCO-pytorch/inference.py", line 24, in
> from loading_pointclouds import *
> File "/home/l/workspace/python/DiSCO-pytorch/loading_pointclouds.py", line 11, in
> import gpuadder
> ModuleNotFoundError: No module named 'gpuadder'

I'll try to reproduce this error, could you provide your dependencies version, it'll be very helpful.

**Comment by lilin-hitcrt** [comment]
> > > You may try to add path to the system path to include gpuadder, I suggest not use the cdll load api.
> > > I found that it is included in the sys path but still cannot be loaded.
> > 
> > 
> > ['/home/l/workspace/python/DiSCO-pytorch', '/home/l/workspace/catkin_ws/devel/lib/python2.7/dist-packages', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/home/l/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/home/l/workspace/python/DiSCO-pytorch']
> > Traceback (most recent call last):
> > File "/home/l/workspace/python/DiSCO-pytorch/inference.py", line 24, in
> > from loading_pointclouds import *
> > File "/home/l/workspace/python/DiSCO-pytorch/loading_pointclouds.py", line 11, in
> > import gpuadder
> > ModuleNotFoundError: No module named 'gpuadder'
> 
> I'll try to reproduce this error, could you provide your dependencies version, it'll be very helpful.

I solved this problem by changing the python version to 3.7. Now I meet a new problem about rfft, I think this is caused by the version of pytorch (1.8.0).

**Comment by lilin-hitcrt** [comment]
> > > > You may try to add path to the system path to include gpuadder, I suggest not use the cdll load api.
> > > > I found that it is included in the sys path but still cannot be loaded.
> > > 
> > > 
> > > ['/home/l/workspace/python/DiSCO-pytorch', '/home/l/workspace/catkin_ws/devel/lib/python2.7/dist-packages', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/home/l/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/home/l/workspace/python/DiSCO-pytorch']
> > > Traceback (most recent call last):
> > > File "/home/l/workspace/python/DiSCO-pytorch/inference.py", line 24, in
> > > from loading_pointclouds import *
> > > File "/home/l/workspace/python/DiSCO-pytorch/loading_pointclouds.py", line 11, in
> > > import gpuadder
> > > ModuleNotFoundError: No module named 'gpuadder'
> > 
> > 
> > I'll try to reproduce this error, could you provide your dependencies version, it'll be very helpful.
> 
> I solved this problem by changing the python version to 3.7. Now I meet a new problem about rfft, I think this is caused by the version of pytorch (1.8.0).

Resuming From  ./log/occ_model.ckpt
Traceback (most recent call last):
  File "inference.py", line 217, in <module>
    disco = infer(cfg.INPUT_FILENAME)
  File "inference.py", line 60, in infer
    out, _, _, _ = infer_model(model, corr2soft, query)
  File "inference.py", line 79, in infer_model
    out, outfft, fft_result, unet_out = model(feed_tensor)
  File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/l/workspace/python/DiSCO-pytorch/models/DiSCO.py", line 323, in forward
    out, fft_result = self.forward_fft(unet_out)
  File "/home/l/workspace/python/DiSCO-pytorch/models/DiSCO.py", line 295, in forward_fft
    median_output = torch.rfft(input, 2, normalized=True, onesided=False)
AttributeError: module 'torch' has no attribute 'rfft'

**Comment by MaverickPeter** [comment]
> Resuming From ./log/occ_model.ckpt
> Traceback (most recent call last):
> File "inference.py", line 217, in
> disco = infer(cfg.INPUT_FILENAME)
> File "inference.py", line 60, in infer
> out, _, _, _ = infer_model(model, corr2soft, query)
> File "inference.py", line 79, in infer_model
> out, outfft, fft_result, unet_out = model(feed_tensor)
> File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/l/workspace/python/DiSCO-pytorch/models/DiSCO.py", line 323, in forward
> out, fft_result = self.forward_fft(unet_out)
> File "/home/l/workspace/python/DiSCO-pytorch/models/DiSCO.py", line 295, in forward_fft
> median_output = torch.rfft(input, 2, normalized=True, onesided=False)
> AttributeError: module 'torch' has no attribute 'rfft'

It seems that the API of torch fft has been modified to support complex variables since 1.7.0, I'll update it ASAP. If you want to use the pre-trained model, I suggest using torch < 1.7.0.

**Comment by lilin-hitcrt** [comment]
> > Resuming From ./log/occ_model.ckpt
> > Traceback (most recent call last):
> > File "inference.py", line 217, in
> > disco = infer(cfg.INPUT_FILENAME)
> > File "inference.py", line 60, in infer
> > out, _, _, _ = infer_model(model, corr2soft, query)
> > File "inference.py", line 79, in infer_model
> > out, outfft, fft_result, unet_out = model(feed_tensor)
> > File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
> > return self.module(*inputs[0], **kwargs[0])
> > File "/home/l/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/home/l/workspace/python/DiSCO-pytorch/models/DiSCO.py", line 323, in forward
> > out, fft_result = self.forward_fft(unet_out)
> > File "/home/l/workspace/python/DiSCO-pytorch/models/DiSCO.py", line 295, in forward_fft
> > median_output = torch.rfft(input, 2, normalized=True, onesided=False)
> > AttributeError: module 'torch' has no attribute 'rfft'
> 
> It seems that the API of torch fft has been modified to support complex variables since 1.7.0, I'll update it ASAP. If you want to use the pre-trained model, I suggest using torch < 1.7.0.

I have resolved this issue by changing the pytorch version to 1.6, thanks for your prompt reply!
