### ISSUE TITLE
Question about No module named 'gputransform'

### ISSUE THREAD

**Issue by jiu876** [MaverickPeter/DiSCO-pytorch#3]
hi,the work is excellent,but when I run the instructionrosrun disco_ros infer_ros.py, there is a error :ModuleNotFoundError: No module named 'gputransform'.how to solve it?Thanks!

**Comment by MaverickPeter** [comment]
@jiu876  hi, the gputransform is built from the cython. Have you followed the instructions to build the library in [multi-layer-polar-cython](https://github.com/MaverickPeter/DiSCO-pytorch/tree/main/multi-layer-polar-cython)/[cython](https://github.com/MaverickPeter/DiSCO-pytorch/tree/main/multi-layer-polar-cython/cython) and put it in the main dir?

**Comment by jiu876** [comment]
@MaverickPeter thanks,I will have a try.One more question, I haven't installed cuda and cudnn yet, whether the code can run normally. If I want to use a GPU, can I install cuda10.0 to meet the requirements?Thanks!

**Comment by MaverickPeter** [comment]
@jiu876  We found that our model also works well in CPU-based PyTorch, it only takes 50-80ms an inference. If you want to use GPU, the version of dependencies should follow the instructions of PyTorch. This version of DiSCO is only supports PyTorch < 1.5.0.

**Comment by jiu876** [comment]
@MaverickPeter I successfully install the library in [multi-layer-polar-cython,and put the pre-model in log(occ_model.ckpt),but when I run the instruction rosrun disco_ros infer_ros.py ,TypeError: __init__() got an unexpected keyword argument 'global_feat'?how to solve it ,thanks!
![c转c++错误](https://user-images.githubusercontent.com/44089510/157254167-287a2704-08bd-4f60-9f07-9ae05381b6f1.png)

**Comment by jiu876** [comment]
@MaverickPeter  I successfully install the library in [multi-layer-polar-cython,and put the pre-model in log(occ_model.ckpt),but when I run the instruction rosrun disco_ros infer_ros.py ,TypeError: init() got an unexpected keyword argument 'global_feat'?how to solve it ,thanks!
![屏幕截图 2022-03-08 22:08:51](https://user-images.githubusercontent.com/44089510/157254317-d566763d-2c06-40b3-9104-04c0361f7305.png)

**Comment by MaverickPeter** [comment]
@jiu876  Sorry for the late reply. I've updated the infer_ros.py changing the error line to "model = SC.DiSCO(output_dim=cfg.FEATURE_OUTPUT_DIM)". The pre-trained model will be uploaded ASAP.

**Comment by jiu876** [comment]
@MaverickPeter I changed the file,but there is another problem.
![aaaa](https://user-images.githubusercontent.com/44089510/157447989-8c67ee79-565f-4c5b-a8ff-d8ec34735db5.png)

**Comment by jiu876** [comment]
@MaverickPeter Thanks a lot, do you have a dataset here, I can try to get the pretrained model by myself

**Comment by MaverickPeter** [comment]
@jiu876  If you can wait, I'll train a model this week. The dataset is over 30GB which I cannot find a good way to share. I recommend you to download it through NCLT official website (http://robots.engin.umich.edu/nclt/).

**Comment by jiu876** [comment]
@MaverickPeter I haven't used NCLT yet，so what does the preparing data occ_0.5m and occ_3m mean? It means the Ground Truth Covariance?
And I  use non-learning disco to infer, the process time is  about 0.15~0.2s,but your result is about 0.05~0.08s,how to speed it up?Thanks!

**Comment by jiu876** [comment]
@MaverickPeter  I haven't used NCLT yet，so what does the preparing data occ_0.5m and occ_3m mean? It means the Ground Truth Covariance?
And I use non-learning disco to infer, the process time is about 0.15-0.2s,but your result is about 0.05-0.08s,how to speed it up?Thanks!

**Comment by MaverickPeter** [comment]
@jiu876  Preparing data occ_0.5m occ_3m means make dirs named "occ_0.5m" and "occ_3m" under the dataset dir. 
As for non-learning disco inference time, it's up to different configurations. What is your hardware setting? Mine is AMD Ryzen 3700X. Also, the output process time includes reading point cloud time. If your input point cloud is large, it'll cost a large amount of time for reading points from the topic. You can add some probes to find the time-consuming module.

**Comment by MaverickPeter** [comment]
@jiu876  I‘ve uploaded a pre-trained model, you can download it through google drive.

**Comment by jiu876** [comment]
@MaverickPeter There is a problem with the uploaded pre-training model, the format is wrong?
![image](https://user-images.githubusercontent.com/44089510/157787198-55cab345-d2c3-40ee-acec-c01829f14f1e.png)

**Comment by MaverickPeter** [comment]
@jiu876  You just have to download the whole model.ckpt. Don't use the "open with" method provided by google drive, it reveals the real data structure in the ckpt file, but we need it whole.

**Comment by jiu876** [comment]
@MaverickPeter the whole model in ubuntu is zip,not binary file？
![屏幕截图 2022-03-11 10:19:24](https://user-images.githubusercontent.com/44089510/157789901-1733550c-fd8d-4b2a-9f1a-3c976aeca5fb.png)

**Comment by MaverickPeter** [comment]
@jiu876 A ckpt file is not a zip. It's a pytorch model file that saves the relative model parameters. It can be easily loaded into pytorch.

**Comment by jiu876** [comment]
@MaverickPeter What I mean is that the newly uploaded pre-training format is wrong. The left side of the picture is the previous pre-training model (which is a binary file)
![屏幕截图 2022-03-11 14:56:28](https://user-images.githubusercontent.com/44089510/157818014-b50b7d99-be00-44a4-82bf-354243729bdb.png)

**Comment by jiu876** [comment]
@MaverickPeter In addition, I would also like to ask, how to make my own data set, I only have a 16-line lidar now, how to obtain the groundtrush.csv(or use RTK to get)?Thanks a lot.

**Comment by jiu876** [comment]
@MaverickPeter What I mean is that the newly uploaded pre-training format is wrong. The left side of the picture is the previous pre-training model (which is a binary file)
![屏幕截图 2022-03-11 14:56:28](https://user-images.githubusercontent.com/44089510/157832936-4ff4bbfe-e237-46c7-bd7b-52170ec22b00.png)
 In addition, I would also like to ask, how to make my own data set, I only have a 16-line lidar now, how to obtain the groundtrush.csv(or use RTK to get)?Thanks a lot.

**Comment by jiu876** [comment]
@MaverickPeter I try to train the model，but when I  use the instruction python generate_training_tuples_baseline_with_pose.py,there is a error:
![参数设置问题](https://user-images.githubusercontent.com/44089510/157833367-a13e92f0-4eaf-469d-bbc2-f80907872e8c.png)

**Comment by MaverickPeter** [comment]
@jiu876  I've figured out the ckpt problem. I've trained my model in PyTorch 1.6.0 which has updates on serialization, so the model trained on PyTorch 1.6 cannot be used in 1.4 unless explicitly set the "_use_new_zipfile_serialization=False" in torch.save. I'm training a new model now and will update the link.
As for the data preparation, it seems that there are some problems with the point cloud file. Can you check the file integrity and the size of the point cloud.

**Comment by jiu876** [comment]
@MaverickPeter I have checked the file integrity and the size of the point cloud many times,but there is still a error,I have changed the base_path,runs_folder and BASE_DIT.
![问题](https://user-images.githubusercontent.com/44089510/158499623-c0f5544a-5bb3-40d1-999a-0836a700b9ab.png)
Is there anything else in the code that needs to be changed?
![bbb](https://user-images.githubusercontent.com/44089510/158499676-ccd7a8fc-877e-4d1a-ba56-80a2c1b49131.png)

**Comment by jiu876** [comment]
@MaverickPeter I tried to use Netron tool to visualize the model（.ckpt）, but the following figure only shows a part of the network structure. Is there any way to fully visualize the network?Thanks a lot!
![model](https://user-images.githubusercontent.com/44089510/158555108-ae18f1db-40fa-4124-8485-64ab4df6b830.png)

**Comment by jiu876** [comment]
@MaverickPeter When I used the instruction to generate the test_sets,there is a error,how to solve it?Thanks!
![cccc](https://user-images.githubusercontent.com/44089510/158600347-ff0c83f1-b8f3-498b-bbfc-a280ea77a55c.png)

**Comment by MaverickPeter** [comment]
@jiu876  You need first generate training sets before generating test sets. I'm working on the training set issue. Please wait a minute.

**Comment by MaverickPeter** [comment]
@jiu876  I got it. This line https://github.com/MaverickPeter/DiSCO-pytorch/blob/8e79286f05f912e1c4596aacf440f56e68cc4e31/generating_queries/nclt/generate_training_tuples_baseline_with_pose.py#L109 is too strict for the error point cloud because, in that frame, all points are lied in [-5m, 5m]. You can change it to the "if np.abs(x) < 70. and z > -20. and z < -2. and np.abs(y) < 70. and not(np.abs(x) < 1. and np.abs(y) < 1.):"

**Comment by jiu876** [comment]
@MaverickPeter Thanks a lot!Now,I try to use Netron tool to visualize the model（.ckpt）, but the following figure only shows a part of the network structure. Is there any way to fully visualize the network?
![image](https://user-images.githubusercontent.com/44089510/158720260-11e3e86b-3548-4990-88e8-d58ec2962d4d.png)

**Comment by MaverickPeter** [comment]
@jiu876  I don't know much about visualizing the model, you may refer to this link for help: https://towardsdatascience.com/visualizing-your-model-using-tensorboard-796ebb73e98d

**Comment by jiu876** [comment]
@MaverickPeter Does the code need to be changed, because I put both datasets in the same folder？
![dddddd](https://user-images.githubusercontent.com/44089510/158728541-3f8cec3b-5a6b-4708-ba57-7e8701bf04be.png)

**Comment by MaverickPeter** [comment]
@jiu876  You don't need to change these lines, as we only save the first folder to pickle file as our training set. https://github.com/MaverickPeter/DiSCO-pytorch/blob/0e598a8a35e9d1733750ad276a38a8033efc340c/generating_queries/nclt/generate_training_tuples_baseline_with_pose.py#L205-L208

**Comment by jiu876** [comment]
@MaverickPeter I found a bug when I used the generate_training_tuples_baseline_with_pose.py to generate the files gt_occ_test_3m.csv and gt_occ_3m.csv which were so small.It seems that some of the point cloud data is read in very quickly and there are a lot of .npy files missing from the final occ_3m file.

**Comment by jiu876** [comment]
@MaverickPeter  There were two problems when I used train_DISCO.py.
First,I found a bug when I used the generate_training_tuples_baseline_with_pose.py to generate the files gt_occ_test_3m.csv and gt_occ_3m.csv which were so small than gt_occ_test_0.5m.It seems that some of the point cloud data is read in very quickly and there are a lot of .npy files missing from the final occ_3m file.
Secondly,the error showed in picture:
![aaaa](https://user-images.githubusercontent.com/44089510/158828665-6524c648-71c2-4ca4-a274-1b3757c8945c.png)

**Comment by MaverickPeter** [comment]
@jiu876  I suggest you add more datasets for evaluation. As for the size of gt_occ_3m and 0.5m. The gt_occ_3m is sampled every 3m while the gt_occ_0.5m is sampled every 0.5m. It's normal that gt_occ_3m is smaller than 0.5m. Also, I will check the code.
