### ISSUE TITLE
Ground Truth

### ISSUE THREAD

**Issue by ydragon719** [MaverickPeter/DiSCO-pytorch#4]
I am reproducing your article. How do you obtain the loop ground truth value of the dataset?

**Comment by MaverickPeter** [comment]
Hi @ydragon719 , you can refer to 'generating_queries/nclt/generate_training_tuples_baseline_with_pose.py' to check the loop ground truth generation. The loop ground truth is mainly based on the ground truth pose given by the datasets.

**Comment by ydragon719** [comment]
Thank you! I get it.
